### ISSUE TITLE
安装后无效

### ISSUE THREAD

**Issue by king0billy** [tiddly-gittly/TidGi-external-attachments-plugin#3]
拖入pdf还是默认的整个文件复制到tiddle文件夹下。
可以用小型视频/gif演示吗？

**Comment by linonetwo** [comment]
复制到tiddle文件夹下。  x


<img width="453" alt="截屏2024-01-24 21 44 37" src="https://github.com/tiddly-gittly/TidGi-external-attachments-plugin/assets/3746270/c82e2e1a-bc90-48fb-b71a-08e43f371e45"> √

**Comment by king0billy** [comment]
拖入pdf到tidgi窗口，行为还是默认的import窗口（即将整个外部文件复制到tiddle文件夹下）。这个插件到底是干什么用的，我预想的行为是创建一个指向wiki文件夹外的链接。
